# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
#include: package:pedantic/analysis_options.yaml
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
# linter:
#   rules:
#     - camel_case_types

linter:
  rules:
    file_names: false
    public_member_api_docs: true
    prefer_relative_imports: true
    prefer_const_constructors: true

analyzer:
  #   exclude:
  #     - path/to/excluded/files/**
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
